import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="bg-white">
					<nav
						className="mx-auto flex max-w-7xl items-center justify-between  p-6 lg:px-8"
						aria-label="Global"
					>
						<div className="flex">
							<a href="#" className="-m-1.5 p-1.5">
								<span className="sr-only">Your Company</span>
								<Image width={100} height={100} className="h-8 w-auto" src="/favicon.ico" alt="" />
							</a>
						</div>

						<div className="flex flex-row gap-x-3">
							<ActiveLink href="/">Home</ActiveLink>
							<ActiveLink href="/products">Products</ActiveLink>
						</div>

						<div>
							<Link
								href="#"
								className="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
							>
								Log in
							</Link>
						</div>
					</nav>
				</header>
				<section className="mx-auto max-w-md p-12 sm:max-w-2xl md:max-w-3xl lg:max-w-6xl ">
					{children}
				</section>
				<footer className="mx-auto flex max-w-7xl items-center justify-center p-6 lg:px-8">
					<p className="max-auto"> &copy; 2023</p>
				</footer>
			</body>
		</html>
	);
}
